### ISSUE TITLE
compatibility to TYPO3 8 LTS

### ISSUE THREAD

**Issue by fischhase** [web-vision/typo3-ter-ameos_filemanager#3]
Hallo,
thank you for your work. Are you planning to bring your EXT to TYPO3 8 LTS? I tried to install it. There is a little work to be done in the ext_table.php (change `t3lib_extMgm::` to `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::`). Then it could be installed, but following things are not working:

1. After scanning the fileadmin folder, there ist a sql error. It can be repaired by analysing the database structure in the install tool (I am not sure if the changes are solve the sql problem)
2. In the frontend plugin form in "Storage" the folder structur of fileadmin ist not listed
3. The field  "Root Ordner" only shows one entry: "Ordner", but the selection of this folder gets lost by saving. So the CE always shows a red mark.

I could not check the frontend view.

It would be great if you spend a little time.
Thank you and bye
Martin

**Comment by DanielSiepmann** [comment]
First of all, it's not our extension, we just ported the existing Extension to TYPO3 7 as the original authors did not do this at the time.

In the meantime they ported the official extension to 7.x, see https://typo3.org/extensions/repository/view/ameos_filemanager
Perhaps it's also compatible with TYPO3 8.x, did you try that? In that case, please report back to us, so we can add a hint at the readme, so others will notice, too.

Also if it's not compatible, please contact pierre@ameos.com (taken from the docs: https://docs.typo3.org/typo3cms/extensions/ameos_filemanager/) whether they plan to migrate.

Otherwise you can come back to us and we will have a look whether we will port it.

Hopefully that feedback will help you.

**Comment by fischhase** [comment]
Hallo Daniel,
sorry, I thought, its your extension. I wrote a mail to pierre and let you know.
Martin

**Comment by DanielSiepmann** [comment]
Thanks Martin, and you're welcome.

I'll keep this issue open until we receive your feedback.

**Comment by fischhase** [comment]
Hallo Daniel,

ameos released a new version. Thats works well for me. One issue will change in the next version: If you edit or delete a file/folder, you actually get back to the root directory, but it should stay in the folder, where you were editing.
current version: https://github.com/ameos/ameos_filemanager/releases/tag/1.1.7

Thanks 
Martin

**Comment by DanielSiepmann** [comment]
Thanks Martin,

I've added a note to the readme to not use this repository any longer, but the official one again.
As some might use this with composer we will keep the repository.
